### ISSUE TITLE
Crashing as of latest changes

### ISSUE THREAD

**Issue by dandelionmane** [vicfryzel/xmonad-config#24]
I've been using your xmonad config for a few days. Today I noticed your recent changes and decided to try them out; I unlinked my .xmonad file and used the new directory and .xsession file. I then reloaded.

I was greeted with a strange view of my desktop background with a red box in the center. I tried logging out to see if re-logging in would fix it. On all my subsequent attempts to log into xmonad, the screen flashed to a black teleprompt for a moment, and then flashed back to the login screen.

Happy to provide debugging information if you tell me what to look for.

**Comment by vicfryzel** [comment]
Hey!

Did you relink ~/.xsession to ~/.xmonad/xmonad-session-rc? I changed the name of this file a while ago, but in my merge today I could have caused some breakage for folks who were linking against the old xsession file.

-Vic

**Comment by vicfryzel** [comment]
Also I had a bug in the xmonad-session-rc file where starting stalonetray was done synchronously. I've since fixed that as of HEAD.

**Comment by dandelionmane** [comment]
Yep, I have .xsession linked properly. I'm going to run a git bisect and try to see which commit broke it.

**Comment by vicfryzel** [comment]
The other major change I made today was to remove gnome-session from xmonad-session-rc. Can you check if reverting the last line in that file to gnome-session fixes it for you?

**Comment by dandelionmane** [comment]
Ok, I reverted the gnome-session line. Now, reloading doesn't crash me, but it does show a compiler error:
xmonad.hs:363 not in scope: dockStartupHook

**Comment by dandelionmane** [comment]
I started seeing the compiler error during the git bisect so I might be in a strange state now.

**Comment by vicfryzel** [comment]
Alt+Shift+q should recompile if you can make it into xmonad. If not, remove the xmonad.* files in ~/.xmonad (obviously not xmonad.hs). Also you can try `cat ~/.xmonad/xmonad.errors` to see what errors are coming up.

**Comment by vicfryzel** [comment]
Oh, sorry just saw your other reply. Which version of xmonad are you running? I fixed a bug introduced in xmonad 0.12 today that caused xmobar to not be properly docked.

**Comment by dandelionmane** [comment]
I'm using xmonad 0.12.
Checking out master (which was broken for me before) now won't compile (Alt+q just shows me the docksStartupHook compiler warnings). So I can no longer repro the bug, in favor of this compiler issue. There must be some state outside of the xmonad-config git repository that changed, but I don't know what it might be.

**Comment by dandelionmane** [comment]
Oh, just realized you said to remove the other xmonad files. I've done that, and reloaded. I'm now in the broken state on my main workspace, ie. I see a black box and my terminal is gone. Interestingly, this chrome tab is working fine in workspcae 2.

**Comment by dandelionmane** [comment]
* This is after taking your suggestion to revert the gnome-session commit, btw.

**Comment by dandelionmane** [comment]
On (broken) window 1, there is a red box surrounding the screen. Moving the mouse near the edge of the box changes the box color from red to grey.

**Comment by dandelionmane** [comment]
alt+p still brings me a program launch menu. gnome-calculator launches, but trying to launch google-chrome or firefox has no discernable effect. I think maybe calculator works because it floats.

**Comment by vicfryzel** [comment]
Oh, I see. I just committed/pushed a fix. You're on 0.12, but I updated the min requirements to 0.13. xmonad introduced a bug in 0.12, and a new hook called docksStartupHook in 0.13. I was referencing docksStartupHook, which broke you on 0.12. Can you pull again and retry?

**Comment by dandelionmane** [comment]
Will do!

**Comment by dandelionmane** [comment]
Ok, taking your new commit and reverting the gnome-session change puts me back in a usable state. But if I just take your new commit without starting gnome-session, it's still broken.

**Comment by dandelionmane** [comment]
Also, the xmobar works for me now, for the first time :)

**Comment by vicfryzel** [comment]
Okay got it. Can you tell me: what settings/session are you choosing from your login manager? Do you have xmonad w/ gnome support installed?

What distro are you on? If you're on debian I should be able to repro locally.

And yeah, xmobar wasn't displaying as a dock for a long time (thus the 0.12 and 0.13 nonsense).

**Comment by dandelionmane** [comment]
I'm on Ubuntu 16.04. I don't actually know the answers to your first questions (I just got seriously started with linux recently), but if you tell me how to check I'll report back. 

If 'login manager' means the screen where I type in my password, I start xmonad by clicking the small circle next to the password box, and choosing "XMonad" in the dropdown.

**Comment by vicfryzel** [comment]
Oh. Okay I think I've figured it out.

`sudo apt-get install consolekit`

Sorry this is my mistake. I rely on consolekit (see `ck-launch-session` in xmonad-session-rc) and yet I somehow didn't put it in the requirements.

Can you let me know if it works from a clean HEAD after you install consolekit?
